### ISSUE TITLE
Add an option for height, or location movement

### ISSUE THREAD

**Issue by LFGaming** [replaceitem/symbol-chat#1]
The icon selection thing sits right infront of any scoreboard that are activated, so i cant read the icons that well. It would be nice if the selection screen could be configured to fix this problem,
Image below is what i mean
![image](https://user-images.githubusercontent.com/38732192/128701230-15750d61-8e55-40d4-a99a-596cc1fe7877.png)

LFGaming,

**Comment by replaceitem** [comment]
Solved by a4c6f08290905e5ee5f3429d87df574fc07792d8
