### ISSUE TITLE
Add the ability to send a group of symbols clicking just once.

### ISSUE THREAD

**Issue by Ahydul1** [replaceitem/symbol-chat#10]
For example with kaomoji, clicking once you could send things like these: ( ´-ω･)︻┻┳══━一   ｡ﾟ(ﾟ´Д`ﾟ)ﾟ｡   (˘⌣˘ )

**Comment by Konijnebeer** [comment]
Some of those Unicode caracters won’t work in minecraft btw

**Comment by Ahydul1** [comment]
Those do, that's not the point.

**Comment by Konijnebeer** [comment]
you could use a macro mod a lot of them exist :)

**Comment by replaceitem** [comment]
How about having a new tab for kaomojis, with the ability to add custom ones?

**Comment by replaceitem** [comment]
Kaomojis and custom strings longer than one characters are now supported
17e576608b4cafbd931b625a87344b52e18159f7
