### ISSUE TITLE
Feature request: HUD button elements

### ISSUE THREAD

**Issue by mrniddala** [replaceitem/symbol-chat#13]
Hello, great mod!
I would love to have the option to deactivate the settings button.
And integrate the settings optionally via Mod Menu.

Greetings 😊

**Comment by replaceitem** [comment]
Makes sense 👍

**Comment by replaceitem** [comment]
Added in e5e67254525952b04519f9f55f9717315637bf49

**Comment by mrniddala** [comment]
Thank you so much ❤️
