### ISSUE TITLE
Button overlap

### ISSUE THREAD

**Issue by ManInMyVan** [replaceitem/symbol-chat#16]
A few buttons overlap with ones from [No Chat Reports](https://modrinth.com/mod/no-chat-reports/) in the chat menu

**Comment by replaceitem** [comment]
Fixed buttons not being clickable in 893872bf4dff32084cacfc97aec6a2200cbd5d2a
The fact that they overlap is just unavoidable, theres always gonna be some mod putting things in the same place, but maybe a toggle for having the menu left/right could be added at some point
