### ISSUE TITLE
Issue with click events

### ISSUE THREAD

**Issue by Warriorrrr** [replaceitem/symbol-chat#18]
When using the mod, all click events don't seem to work. For example, the following command would send a message that opens chat with the /gamemode command pre-typed, but this does not work.
```
/tellraw @p {"text":"click me","clickEvent":{"action":"suggest_command","value":"/gamemode"}}
```

Tested with version 0.4.2 & fabric API version 0.68.0, no other mods were present.

**Comment by replaceitem** [comment]
Fixed in 368a6601b3964005d9ef3b917bcdf725c4d74812
