### ISSUE TITLE
Mod Incompatibility with Stendhal

### ISSUE THREAD

**Issue by Caketaco** [replaceitem/symbol-chat#22]
When attempting to type in a sign with both Symbol Chat and Stendhal installed, the game crashes.

<details><summary>Example Crashes:</summary>

Quilt 1.19.2 _(Although I have seen similar results on other clients)_
[Client Log](https://mclo.gs/yjgLZaH)
[Crash Log](https://mclo.gs/vZqngRe)
</details>

The mod author of Stendhal's solution to this is offering most of what Symbol Chat offers (They already have unicode symbols, but they lack unicode fonts, which they plan on adding.)

![image](https://user-images.githubusercontent.com/39420594/213949585-64359799-6ca6-4d47-8342-4db0d63c2bf5.png)

While this would fix the issue in some regard, it would be much nicer if both mods could still work together, as I much prefer the aesthetics of Symbol Chat over Stendhal.

If you want to talk about it with the developer directly, their discord server is [here](https://discord.gg/6StChT5m2V), and a discussion about this issue appears [here](https://discord.com/channels/826836207454388225/826842299341865001/1066054729253265518) in the server.

**Comment by replaceitem** [comment]
I added some extra checks in 29b52d8626344f3e3c4c1cd192526a1940b134c4, which could have fixed this. I did not check that, but it might be considering the crash log you sent.
