### ISSUE TITLE
Use (:) to select special characters

### ISSUE THREAD

**Issue by Aces-and-Jacks** [replaceitem/symbol-chat#24]
So like if I do :anchor then it'll auto suggest ⚓

**Comment by replaceitem** [comment]
Added in a6eaa330b636ceee9e6ec6d99af87442a57c8777

**Comment by replaceitem** [comment]
Fixed in 492c078b07d41b6083ea8e31ca5e7bec68fbfb3a

**Comment by Felix14-v2** [comment]
Thanks!
