### ISSUE TITLE
Client crashes when open anvils GUI

### ISSUE THREAD

**Issue by YumatanGames** [replaceitem/symbol-chat#28]
Hi. I had a weird client side crash when opening Anvils and I assume it's because I have Better Anvils installed. 

I hope the log helps figuring out what's happening. 
Thanks

[crash-2023-03-21_10.25.36-client.txt](https://github.com/replaceitem/symbol-chat/files/11032665/crash-2023-03-21_10.25.36-client.txt)

**Comment by replaceitem** [comment]
This was already fixed in 29b52d8626344f3e3c4c1cd192526a1940b134c4, but that means it's only fixed in version 0.7.1 upwards (Minecraft 1.19.3)

**Comment by YumatanGames** [comment]
Oh, ok. Sorry, my server is running on 1.19.2, so I didn't knew it was fixed. Is there any plans on backporting it to 1.19.2? 

Thanks anyway. :D

**Comment by replaceitem** [comment]
Alright i fixed it in a 1.19.2 version too now. I added a 0.5.2 file to the 0.5.1 Modrinth version: https://modrinth.com/mod/symbol-chat/version/0.5.1

**Comment by YumatanGames** [comment]
You're so nice to do that, really appreciate it.

Thank you so much.
