### ISSUE TITLE
[Feature request] Add scrolling on large tabs

### ISSUE THREAD

**Issue by Felix14-v2** [replaceitem/symbol-chat#3]
Now there are a huge number of other interesting symbols that do not have their own tab or have been missed in existing tabs. I started adding them to a custom tab, but quickly ran into a space limit. Maybe it is possible to add the ability to scroll in tabs whose size is larger than the window size?

<details>
 <summary>Example</summary>

![image](https://user-images.githubusercontent.com/75726196/162771618-8e5c35fc-d1cb-4da6-a795-a803034ba815.png)

</details>

<details>
 <summary>Used Symbols/Groups</summary>

`⚐🧪⏻⚓⛨�⁇⁈`
`✂✁✃✄❌ƒ≠ꝏ`
`♩♪♫♬♭♮♯☐`
`☑☒⚀⚁⚂⚃⚄⚅`
`₽$€£¥₿₡₮`
`™©®℗❂✪⯪⯫`
`✦✧✫✩✰✯✭⚝`
`❀✿❁✵❃✾✼❉`
`✷❋✺✹✸✴✳✶`
`❄✻❊❆❅❇❈✠`
`↱↲↳↰↻↶↷↺`
`⇦⇧⇩⇨⇘⇖⇗⇙`
`⇇⇆⇉⇚⇛⇈⇅⇊`
`➩➪➯➱➭➮➫➬`
`➢➣➤➡➲➘➙➚`
`⏴⏵⏶⏷*⁎⁑⁂`
`⤫⤬⤰⤯⤲⤱⤮⤭`
`ⅠⅡⅢⅣⅤⅥⅦⅧ`
`ⅨⅩⅪⅫⅬⅭⅮⅯ`
</details>

**Comment by replaceitem** [comment]
Yeah scrolling is definetly needed

As a sidenote, if you don't mind, could you create an issue with all those symbols as text? I would like to add some of them.

**Comment by Felix14-v2** [comment]
> issue with all those symbols

Maybe later, I'm just starting to add them... But I added the current list to the previous comment.

**Comment by replaceitem** [comment]
Alright thanks!
