### ISSUE TITLE
Cant edit chat when pressing the arrow key to go back to the last message

### ISSUE THREAD

**Issue by JACTC** [replaceitem/symbol-chat#39]
When you get the last message/command from chat using the arrow keys(default) you are not able to edit the message/command.

How to replicate:
- type in chat
- open chat and press the arrow key to get the last message 
- try to edit the message

**Comment by replaceitem** [comment]
Is this on the latest version 1.1.1, and do you have any other mods?

**Comment by JACTC** [comment]
Thank you so much!
