### ISSUE TITLE
Texts showing up like squares

### ISSUE THREAD

**Issue by GameVPR** [replaceitem/symbol-chat#40]
All the texts showing up like this:
▓▓▓▓▓
▓ ​ ​ ​ ​ ​ ​ ​ ▓
▓ ​ ​ ​ ​ ​ ​ ​ ▓
▓ ​ ​ ​ ​ ​ ​ ​ ​▓
▓▓▓▓▓

Fabric 0.14.22 for 1.20.1
Java: Multiple versions (including 20.0.2)
Uncompatible with: IDK

**Comment by GameVPR** [comment]
I dont use resource packs. So no.

**Comment by replaceitem** [comment]
Does literally every character in text show as a rectangle?
What mods do you use?
If you remove symbol-chat, does that fix it?

**Comment by GameVPR** [comment]
If i delete symbol-chat it fixes and yes, every text you can see is just squares like i sented in first comment.
I use over 200 mods, its a vanilla+/vanilla++ type modpack. But if its necessary i can give you list.

**Comment by replaceitem** [comment]
That's weird, symbol chat doesnt change any of the text rendering, it only adds tools to insert characters. What version of symbol chat are you using?
Could you send a link to the modpack?

**Comment by GameVPR** [comment]
I added the mod back, it shown up every text normally but my game crashed im testing the mod..
[ This section gonna be update ]

**Comment by replaceitem** [comment]
Alright cool, i couldn't imagine how this mod could break text rendering, so glad its resolved
