### ISSUE TITLE
incompatibility with no chat reports (and possibly other mods)

### ISSUE THREAD

**Issue by CapToad** [replaceitem/symbol-chat#42]
for example when you hover over the button to change signing mode the text doesnt appear and just displays a blank rectangle
other mods are also affected (codeclient) but thats all i know
![obraz](https://github.com/replaceitem/symbol-chat/assets/127859879/0458b745-f88b-4405-8926-1ab9ae3caf44)

**Comment by replaceitem** [comment]
What version of Minecraft, SymbolChat and NoChatReports are you using?

**Comment by CapToad** [comment]
symbol chat 1.2.2
minecraft 1.20.4
no chat reports 2.6.1

**Comment by replaceitem** [comment]
In the latest version for MC 1.21 this seems to no longer be a problem, and i don't really support MC 1.20.4 anymore. My guess would be that this is not a problem on 1.20.4 if you use SymbolChat 1.2.1 since 1.2.2 changed quite a lot on the rendering.
