### ISSUE TITLE
Crash Minecraft

### ISSUE THREAD

**Issue by FaNToMaSikkk** [replaceitem/symbol-chat#44]
### Describe the bug
I have crashes minecraft when using Symbol Chat and [Scribble](https://modrinth.com/mod/scribble), separately these two mods work fine, but together they conflict with each other.
### To Reproduce

1. Enter the game
2.  Open the book
3. Write any text (With fonts or without, does not make any difference)
4. Save the text for the first time
5. In the second time select all the text and delete it then save the book.

#### Crash Report/Video
[crash-2024-07-03_12.24.23-client.txt](https://github.com/user-attachments/files/16082009/crash-2024-07-03_12.24.23-client.txt)
[Video](https://www.youtube.com/watch?v=METwvDftYy8)

### Basic Informations

- OS Windows 11
- Symbol Chat 1.1.2
- Fabric Version 0.15.11
- Version Minecraft 1.20.1
- Active Mods:
    - Fabric API 0.92.2
    - [Scribble](https://modrinth.com/mod/scribble) 1.0.1
    - Cloth Config API 11.1.118
    - Symbol Chat 1.1.2
    - Mod Menu 7.2.2

**Comment by replaceitem** [comment]
Fixed by https://github.com/chrrs/scribble/commit/837a91d0be6ea567b8a8b2e8a23c953be27ff6db
