### ISSUE TITLE
[Create A New Mod] Chat Keyboard

### ISSUE THREAD

**Issue by Zack694** [replaceitem/symbol-chat#54]
So can you make a mod in chat that has a floating Keyboard (Half keyboard/No Number pad)? because some of my keys aren't working and it's expensive to buy a new one

**Comment by replaceitem** [comment]
Creating such a mod takes time, which i don't have, and don't want to use for a mod that doesn't interest me. There are probably other solutions for your problem. Windows has a built in onscreen keyboard, and if that doesn't work, there are likely other 3rd party programs that do what you need.
