### ISSUE TITLE
[FEATURE REQUEST] Ability to Move Symbols Menu

### ISSUE THREAD

**Issue by JosTheDude** [replaceitem/symbol-chat#56]
It would be great to be able to move the location of the symbols menu in order to accomodate for other chat mods (i.e. ChatPlus) who utilize the Chat bar which may overlap.

![image](https://github.com/user-attachments/assets/c66c2b93-8cbd-47bc-a7fe-5ce3c8986aed)

I know that other parts of the GUI are movable like the font options, so being able to move the symbols button up there with the font options or anywhere on the screen would be great.
edit: image fix

**Comment by JosTheDude** [comment]
Works for me! I'd love to group it next to the fonts option

**Comment by JosTheDude** [comment]
> Makes sense. Would 4 options for all corners of the screen be enough?

Ello! I just wanted to ask if you know when this'll be bundled with Modrinth releases? (im unsure if you have a guideline for that sort of thing)

**Comment by replaceitem** [comment]
I could upload a new release, yeah. I just didn't do it back when i implemented it because it's just a single minor change. But since there isn't anything on my todo for this mod, i could push a new version.

**Comment by replaceitem** [comment]
https://modrinth.com/mod/symbol-chat/version/a7atsqPu

**Comment by JosTheDude** [comment]
> I could upload a new release, yeah. I just didn't do it back when i implemented it because it's just a single minor change. But since there isn't anything on my todo for this mod, i could push a new version.

Yeah just wanted to ask since it's been a minute. Thank you for the release :)
